version: '3.8'
volumes:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - 'node_modules:/app/node_modules'
    tty: true
    ports:
      - '3000:3000'
